# applications
version: '3'
services:
  web-app:
    build: ./app
    container_name: fastapi
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    ports:
      - "8008:8000"
    depends_on:
      - kafka
      - postgres
      - kafka-producer
    networks:
      - kafka-net