# applications
version: '3'
services:
  web-app:
    build: ./app
    container_name: fastapi
    environment:
      - host=database
      - database=pg
      - user=pg
      - password=pg
    ports:
      - "8008:8000"
    depends_on:
      - kafka
      - postgres
      - kafka-producer
    networks:
      - kafka-net

  angular-app:
    build: ./app/trackingGPSfront
    container_name: angular
    ports:
      - "4200:80"
    depends_on:
      - web-app
    networks:
      - kafka-net
