# producer
version: '3'
services:
  kafka-producer:
    build: ./producer
    container_name: kafka-producer
    environment:
      - KAFKA_BROKER=kafka:9092
      - id=1
      - x=49.43742987885597 
      - y=11.090147027822049
    depends_on:
      - kafka
    networks:
      - kafka-net

  kafka-producer2:
    build: ./producer
    container_name: kafka-producer2
    environment:
      - KAFKA_BROKER=kafka:9092
      - id=2
      - x=45.74505320159049 
      - y=4.8542187705193
    depends_on:
      - kafka
    networks:
      - kafka-net