# producer
version: '3'
services:
  kafka-producer:
    build: ./producer
    container_name: kafka-producer
    environment:
      - KAFKA_BROKER=kafka:9092
      - id=1
    depends_on:
      - kafka
    networks:
      - kafka-net

  kafka-producer2:
    build: ./producer
    container_name: kafka-producer2
    environment:
      - KAFKA_BROKER=kafka:9092
      - id=2
    depends_on:
      - kafka
    networks:
      - kafka-net